### ISSUE TITLE
[Bug] 在 Vue 中使用 VChart, 开发环境正常运行， 打包后在线上出现报错：this.contributions.forEach is not a function

### ISSUE THREAD

**Issue by lhcGinv** [VisActor/VChart#2800]
### Version

1.10.6、1.11.3

### Link to Minimal Reproduction

https://codesandbox.io/s/viscator-vchart-vue-demo-gmcpq6?file=/src/components/LineChart.vue

### Steps to Reproduce

在 Vue 中组合式 API方式使用 VChart
1.开发环境正常运行
2.打包后在线上出现报错

### Current Behavior

在 Vue 中使用 VChart, 开发环境正常运行， 打包后在线上出现报错, 且图表空白：
```
TypeError: this.contributions.forEach is not a function
    at bm.init (vchart-4d6470b5.js:1:424789)
    at new bm (vchart-4d6470b5.js:1:424756)
    at Object._createInstance (vchart-4d6470b5.js:1:126614)
    at Object._resolveInstance (vchart-4d6470b5.js:1:126556)
    at Object._getResolvedFromBinding (vchart-4d6470b5.js:1:126360)
    at Object._resolveFromBinding (vchart-4d6470b5.js:1:126206)
    at vchart-4d6470b5.js:1:126766
    at Array.map (<anonymous>)
    at Object._resolveRequests (vchart-4d6470b5.js:1:126684)
    at Object._createInstance (vchart-4d6470b5.js:1:126628)
```

### Expected Behavior

期望可以修复这个问题，在版本1.10以上都有这个问题

### Environment

```markdown
OS: macOS Monterey
Browser: Chrome 125.0.6422.142
Framework Vue@3.4
```

**Comment by xile611** [comment]
@lhcGinv 有最小复现问题的工程吗？

**Comment by xile611** [comment]
参考这个文档：https://visactor.com/vchart/guide/tutorial_docs/Load_on_Demand
![0db881dc-d5f1-4eac-92a8-36d2baf11115](https://github.com/VisActor/VChart/assets/6111424/3a41f5f2-e5c1-4b6c-a091-0e563948c733)


可以改成 
```
import { default as VChart } from '@visactor/vchart';
```
这样会加载所有的图表类型

**Comment by lhcGinv** [comment]
或者这样写 import VChart from '@visactor/vchart'

**Comment by XPDD** [comment]
我打包也遇到了同样的问题，如果官方可以出一个vue3版本就好了。我感觉我们开发时，其实很难把文档细节看完。
